version: '3.8'

services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.10.0'
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'

  rabbitmq:
    image: 'rabbitmq:3.8-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
